version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: happy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  postgres:
